unit Vms.Server.Events.Html;

// GERADO por tools/gen_ui_pas.py -- NAO EDITE ESTA UNIT.
//
// A fonte e vms/src/Api/events-ui.html. Mexeu la, rode o gerador de novo:
//
//     python tools/gen_ui_pas.py
//
// A pagina e servida em /ui/events pelo Vms.Server.Api.

interface

// A pagina inteira, pronta para servir ou carregar.
function EventsUiHtml: string;

implementation

uses
  System.SysUtils,
  System.Classes;

const
  LINHAS: array[0..295] of string = (
    '<!doctype html>',
    '<meta charset="utf-8">',
    '<meta name="viewport" content="width=device-width, initial-scale=1">',
    '<title>Eventos</title>',
    '<!--',
    '  A faixa de eventos, servida em /ui/events. Feita para viver DENTRO do app,',
    '  numa banda embaixo do video, e nao numa aba de navegador.',
    '',
    '  ## Por que servida, e nao carregada por LoadFromStrings',
    '',
    '  Carregada com base https://vms.local/ ela teria contexto seguro, mas nao',
    '  poderia buscar nada em http://<servidor>:8554 -- seria conteudo misto, e o',
    '  navegador bloqueia. Servida pelo proprio vmsserver, o fetch e mesma origem e',
    '  simplesmente funciona. Aqui nao se decodifica nada, entao contexto seguro nao',
    '  faz falta.',
    '',
    '  ## Como ela fala com o app',
    '',
    '  Pelo unico canal que o FMX oferece: navegacao. O',
    '  TWebBrowser.OnShouldStartLoadWithRequest avisa a URL que a pagina tentou',
    '  abrir, e o app le dali o comando.',
    '',
    '  Repare que a navegacao acontece num IFRAME escondido, e nao na propria',
    '  janela. E deliberado: o FMX so AVISA a URL, ele nao consegue cancelar a',
    '  navegacao (o shouldOverrideUrlLoading do Android devolve False fixo). Se o',
    '  comando fosse na janela principal, a pagina tentaria sair para um esquema que',
    '  nao existe e se perderia. No iframe, quem se perde e o iframe, que ninguem ve.',
    '',
    '  ASCII puro (exigencia do tools/gen_ui_pas.py): acento por entidade na',
    '  marcacao, e por escape unicode nas strings de JavaScript.',
    '-->',
    '<style>',
    '  :root { color-scheme: dark; }',
    '  html, body { height:100%; }',
    '  body { margin:0; background:#121212; color:#e6e6e6; overflow:hidden;',
    '         font:400 13px/18px Roboto, system-ui, "Segoe UI", sans-serif;',
    '         -webkit-tap-highlight-color: transparent; }',
    '',
    '  /* Dois formatos, e a altura decide qual.',
    '     Numa FAIXA (banda baixa embaixo do video) a lista rola na horizontal, como',
    '     uma regua de miniaturas: rolar na vertical em 150px nao mostraria nada.',
    '     Em TELA CHEIA isso fica pessimo -- cartoes altos e estreitos, e o dedo',
    '     rolando para o lado. Ai vira grade, que e o que se espera de uma lista. */',
    '  #barra { display:flex; align-items:center; gap:8px; padding:8px 10px;',
    '           background:#1a1a1a; }',
    '  #titulo { font-size:12px; color:#c2c7c9; white-space:nowrap; }',
    '  #titulo b { color:#e6e6e6; }',
    '  select { background:none; color:#8ed0f0; border:1px solid #3f4447;',
    '           border-radius:16px; padding:5px 10px; font:inherit; }',
    '  #msg { font-size:11px; color:#c2c7c9; margin-left:auto; white-space:nowrap; }',
    '',
    '  #tira { display:flex; gap:8px; overflow-x:auto; overflow-y:hidden;',
    '          padding:8px; height:calc(100% - 36px); box-sizing:border-box;',
    '          -webkit-overflow-scrolling:touch; scrollbar-width:thin; }',
    '  .ev { flex:0 0 auto; width:132px; background:#1f1f1f; border-radius:12px;',
    '        border:2px solid transparent; overflow:hidden; cursor:pointer;',
    '        display:flex; flex-direction:column; }',
    '  .ev.sel { border-color:#8ed0f0; }',
    '  .ev img { width:132px; height:74px; object-fit:cover; background:#000;',
    '            display:block; }',
    '',
    '  /* Acima de 300px de altura nao e mais faixa: e tela. */',
    '  @media (min-height: 300px) {',
    '    #tira { display:grid; gap:10px; overflow-x:hidden; overflow-y:auto;',
    '            grid-template-columns: repeat(auto-fill, minmax(150px, 1fr));',
    '            /* max-content, e nao o `auto` implicito: com a imagem em largura',
    '               percentual e proporcao fixa, a linha automatica nao contava a',
    '               altura dela -- ficava em 60px, a imagem transbordava e o',
    '               overflow:hidden do cartao a cortava numa fatia fina. */',
    '            grid-auto-rows: max-content;',
    '            align-content:start; padding:10px; }',
    '    /* block, e nao flex: dentro da grade o cartao em flex ainda espremia a',
    '       imagem contra a altura da linha. */',
    '    .ev { width:auto; display:block; }',
    '    .ev img { width:100%; height:auto; aspect-ratio:16/9; display:block; }',
    '  }',
    '  .ev .txt { padding:4px 6px 6px; }',
    '  .ev .h { font-size:12px; font-variant-numeric:tabular-nums; }',
    '  .ev .n { font-size:11px; color:#c2c7c9; white-space:nowrap;',
    '           overflow:hidden; text-overflow:ellipsis; }',
    '  .pin { display:inline-block; width:6px; height:6px; border-radius:3px;',
    '         margin-right:5px; vertical-align:1px; }',
    '  .k-motion { background:#f2c14e; }',
    '  .k-object { background:#8ed0f0; }',
    '  #vazio { color:#c2c7c9; font-size:12px; padding:24px 16px; }',
    '</style>',
    '',
    '<div id="barra">',
    '  <span id="titulo"></span>',
    '  <select id="filtro">',
    '    <option value="">tudo</option>',
    '    <option value="object">objetos</option>',
    '    <option value="motion">movimento</option>',
    '  </select>',
    '  <span id="msg"></span>',
    '</div>',
    '<div id="tira"><div id="vazio">carregando...</div></div>',
    '<iframe id="ponte" style="display:none" title=""></iframe>',
    '',
    '<script>',
    '"use strict";',
    '',
    'var q = new URLSearchParams(location.search);',
    'var CAMERA = q.get("camera") || "";',
    'var DE = parseInt(q.get("fromMs") || "0", 10);',
    'var ATE = parseInt(q.get("toMs") || "0", 10);',
    '// O app passa o proprio esquema; sem ele a pagina ainda serve para olhar, so',
    '// nao comanda nada. Assim a mesma pagina abre no navegador para diagnostico.',
    'var ESQUEMA = q.get("scheme") || "";',
    '// De qual servidor vem tudo. Vazio = quem serviu a pagina.',
    'var SERVIDOR = q.get("server") || "";',
    '',
    'function api(caminho) {',
    '  if (!SERVIDOR) return caminho;',
    '  return caminho + (caminho.indexOf("?") >= 0 ? "&" : "?") +',
    '         "server=" + encodeURIComponent(SERVIDOR);',
    '}',
    '',
    '// Dentro de um iframe da casca, quem manda no player e a pagina de fora --',
    '// falar com ela por postMessage e direto e sincrono. Fora dela, sobra o canal',
    '// por navegacao, que e o unico que o FMX oferece.',
    'var DENTRO_DA_CASCA = (window.parent !== window);',
    '',
    'var eventos = [], selecionado = -1;',
    '',
    '// Quantas miniaturas carregam de imediato. O bastante para cobrir a largura de',
    '// uma faixa em tablet deitado; o resto entra conforme rola.',
    'var PRIMEIRAS = 10;',
    'var porCarregar = [];',
    'var observador = null;',
    '',
    'function $(id) { return document.getElementById(id); }',
    'function pad(n) { return (n < 10 ? "0" : "") + n; }',
    'function hora(ms) {',
    '  var d = new Date(ms);',
    '  return pad(d.getHours()) + ":" + pad(d.getMinutes()) + ":" + pad(d.getSeconds());',
    '}',
    '',
    '// O canal para o app. Ver o cabecalho: iframe, e nao location, porque o FMX',
    '// avisa a navegacao mas nao a cancela.',
    'function avisarApp(comando, valor) {',
    '  if (DENTRO_DA_CASCA) {',
    '    // ''*'' porque a origem e a mesma de quem serviu esta pagina, seja o app ou',
    '    // o vmsserver -- fixar uma origem aqui quebraria um dos dois.',
    '    window.parent.postMessage({ vms: comando, ms: valor }, "*");',
    '    return true;',
    '  }',
    '  if (!ESQUEMA) return false;',
    '  $("ponte").src = ESQUEMA + "://" + comando + "?ms=" + valor +',
    '                   "&t=" + Date.now();',
    '  return true;',
    '}',
    '',
    '// Poe a URL no src. Idempotente: chamada duas vezes nao recarrega.',
    'function acender(img) {',
    '  if (!img || !img.dataset.url) return;',
    '  img.src = img.dataset.url;',
    '  delete img.dataset.url;',
    '}',
    '',
    'function pintar() {',
    '  var filtro = $("filtro").value;',
    '  var tira = $("tira");',
    '  if (observador) { observador.disconnect(); observador = null; }',
    '  porCarregar = [];',
    '  tira.innerHTML = "";',
    '  var mostrados = 0;',
    '',
    '  eventos.forEach(function (e, i) {',
    '    if (filtro && e.kind !== filtro) return;',
    '    mostrados++;',
    '    var d = document.createElement("div");',
    '    d.className = "ev" + (i === selecionado ? " sel" : "");',
    '    d.dataset.i = i;',
    '',
    '    var img = document.createElement("img");',
    '    img.alt = "";',
    '    // A URL fica guardada, e nao no src: com centenas de eventos, pedir todas',
    '    // as miniaturas de uma vez afogaria o aparelho e o servidor.',
    '    //',
    '    // Repare que NAO se usa loading="lazy": numa tira de rolagem horizontal ele',
    '    // se mostrou pouco confiavel -- as imagens ficavam presas em complete=false',
    '    // e a faixa aparecia vazia. Aqui o controle e explicito: as primeiras vao',
    '    // direto (ver PRIMEIRAS) e o resto entra por IntersectionObserver ancorado',
    '    // na propria tira.',
    '    img.dataset.url = api("/api/thumb?camera=" + encodeURIComponent(CAMERA) +',
    '                          "&ms=" + e.startMs);',
    '    d.appendChild(img);',
    '    porCarregar.push(img);',
    '',
    '    var txt = document.createElement("div");',
    '    txt.className = "txt";',
    '    var h = document.createElement("div");',
    '    h.className = "h";',
    '    var pin = document.createElement("span");',
    '    pin.className = "pin k-" + (e.kind === "object" ? "object" : "motion");',
    '    h.appendChild(pin);',
    '    h.appendChild(document.createTextNode(hora(e.startMs)));',
    '    var n = document.createElement("div");',
    '    n.className = "n";',
    '    // Evento de objeto traz a classe da rede ("motorcycle"); o de movimento nao',
    '    // tem nome, e o rotulo dele e o proprio tipo.',
    '    n.textContent = e.name || (e.kind === "motion" ? "movimento" : e.kind || "");',
    '    txt.appendChild(h);',
    '    txt.appendChild(n);',
    '    d.appendChild(txt);',
    '',
    '    d.onclick = function () { escolher(i); };',
    '    tira.appendChild(d);',
    '  });',
    '',
    '  if (!mostrados) {',
    '    var v = document.createElement("div");',
    '    v.id = "vazio";',
    '    v.textContent = eventos.length ? "nada neste filtro"',
    '                                   : "nenhum evento neste dia";',
    '    tira.appendChild(v);',
    '  }',
    '  $("msg").textContent = mostrados + " de " + eventos.length;',
    '',
    '  // As primeiras sem esperar observador nenhum: a faixa nunca deve aparecer',
    '  // vazia, e as que estao na tela ao abrir nao dependem de rolagem.',
    '  porCarregar.slice(0, PRIMEIRAS).forEach(acender);',
    '',
    '  var resto = porCarregar.slice(PRIMEIRAS);',
    '  if (!resto.length) return;',
    '  if (!window.IntersectionObserver) {',
    '    // Sem observador (WebView antigo), carrega tudo. Pior para a rede, melhor',
    '    // que uma faixa que nunca mostra imagem.',
    '    resto.forEach(acender);',
    '    return;',
    '  }',
    '  observador = new IntersectionObserver(function (entradas) {',
    '    entradas.forEach(function (en) {',
    '      if (!en.isIntersecting) return;',
    '      acender(en.target);',
    '      observador.unobserve(en.target);',
    '    });',
    '  }, { root: tira, rootMargin: "300px" });',
    '  resto.forEach(function (img) { observador.observe(img); });',
    '}',
    '',
    'function escolher(i) {',
    '  selecionado = i;',
    '  pintar();',
    '  var e = eventos[i];',
    '  if (!e) return;',
    '  if (!avisarApp("seek", e.startMs))',
    '    $("msg").textContent = hora(e.startMs) + " (sem app)";',
    '}',
    '',
    'function carregar() {',
    '  if (!CAMERA || !DE || ATE <= DE) {',
    '    $("tira").innerHTML = ''<div id="vazio">faltou camera ou intervalo</div>'';',
    '    return;',
    '  }',
    '  $("titulo").innerHTML = "<b>" + CAMERA + "</b>";',
    '  var u = api("/api/events?camera=" + encodeURIComponent(CAMERA) +',
    '              "&fromMs=" + DE + "&toMs=" + ATE + "&limit=2000");',
    '  fetch(u).then(function (r) { return r.json(); }).then(function (j) {',
    '    if (j.error) {',
    '      $("tira").innerHTML = ''<div id="vazio"></div>'';',
    '      $("tira").firstChild.textContent = j.error;',
    '      return;',
    '    }',
    '    eventos = j.events || [];',
    '    pintar();',
    '  }).catch(function (err) {',
    '    $("tira").innerHTML = ''<div id="vazio"></div>'';',
    '    $("tira").firstChild.textContent = "falhou: " + err;',
    '  });',
    '}',
    '',
    '// O app chama isto por EvaluateJavaScript quando a reproducao anda, para a',
    '// faixa acompanhar sem que o usuario role atras. E o sentido contrario da',
    '// ponte, e o unico que o FMX faz bem.',
    'window.vmsPosicao = function (ms) {',
    '  var melhor = -1, dist = 1e15;',
    '  for (var i = 0; i < eventos.length; i++) {',
    '    var d = Math.abs(eventos[i].startMs - ms);',
    '    if (d < dist) { dist = d; melhor = i; }',
    '  }',
    '  // Longe demais de qualquer evento: nao faz sentido destacar nenhum.',
    '  if (melhor < 0 || dist > 60000) return;',
    '  if (melhor === selecionado) return;',
    '  selecionado = melhor;',
    '  pintar();',
    '  var el = document.querySelector(''.ev[data-i="'' + melhor + ''"]'');',
    '  if (el && el.scrollIntoView)',
    '    el.scrollIntoView({ block: "nearest", inline: "center" });',
    '};',
    '',
    '$("filtro").onchange = pintar;',
    'carregar();',
    '</script>',
    ''
  );

function EventsUiHtml: string;
var
  SB: TStringBuilder;
  I: Integer;
begin
  SB := TStringBuilder.Create;
  try
    for I := Low(LINHAS) to High(LINHAS) do
    begin
      SB.Append(LINHAS[I]);
      SB.Append(#10);
    end;
    Result := SB.ToString;
  finally
    SB.Free;
  end;
end;

end.
